### ISSUE TITLE
Account Modal overflow

### ISSUE THREAD

**Issue by roiLeo** [paritytech/polkadot-staking-dashboard#1428]
#### What happened
Not possible to scroll in Account Modal

#### Expected Behavior
- replace overflow hidden

#### Screenshot
![Screenshot 2023-09-14 at 11-56-55 Polkadot Staking Dashboard Polkadot Staking (DOT)](https://github.com/paritytech/polkadot-staking-dashboard/assets/9987732/7c54e9de-bae2-4b52-88ac-461514733ad7)

**Comment by rossbulat** [comment]
I am able to scroll still.

**Comment by roiLeo** [comment]
I am able to scroll in "Extension" modal (overflow: scroll) but not in "Accounts" modal (overflow: hidden)
<img width="1146" alt="Capture d’écran 2023-09-14 à 1 01 21 PM" src="https://github.com/paritytech/polkadot-staking-dashboard/assets/9987732/af15a6fd-ec77-4f4e-b02d-f6b70a18f1c3">

**Extension modal**
<img width="476" alt="Capture d’écran 2023-09-14 à 1 01 51 PM" src="https://github.com/paritytech/polkadot-staking-dashboard/assets/9987732/967c24a2-6f9d-4478-b4ed-70a3d04cb271">

**Accounts modal**
<img width="476" alt="Capture d’écran 2023-09-14 à 1 05 06 PM" src="https://github.com/paritytech/polkadot-staking-dashboard/assets/9987732/8b4daa6f-3b91-47be-96d8-75c5aeac0195">


> If the latest update with hidden scrollbar is indeed confusing then i will expedite the custom scrollbar effort with a minor release.

Yes, it's confusing and I personally think it's bad for the UX to hide the scroll bar when scrolling is possible.

**Comment by rossbulat** [comment]
Thanks for additional context. Scrollbars for the modal are now back, and the scrolling should be working again now on https://paritytech.github.io/polkadot-staking-dashboard/#/overview. Can you confirm?

**Comment by roiLeo** [comment]
> Thanks for additional context. Scrollbars for the modal are now back, and the scrolling should be working again now on https://paritytech.github.io/polkadot-staking-dashboard/#/overview. Can you confirm?


https://github.com/paritytech/polkadot-staking-dashboard/assets/9987732/e83e9774-868d-4829-99bb-15a69359dfb8

Still an issue, content behind is scrolling but not in modal

**Comment by rossbulat** [comment]
Thanks, I found the issue and it should be working on https://paritytech.github.io/polkadot-staking-dashboard/#/overview now. I'm preparing a release to go live also.

**Comment by roiLeo** [comment]
> Thanks, I found the issue and it should be working on https://paritytech.github.io/polkadot-staking-dashboard/#/overview now. I'm preparing a release to go live also.

Works now, thanks! (resolved by https://github.com/paritytech/polkadot-cloud/commit/0747c8a07afa6125a363da686255db5c3e646f25?)

**Comment by rossbulat** [comment]
> > Thanks, I found the issue and it should be working on https://paritytech.github.io/polkadot-staking-dashboard/#/overview now. I'm preparing a release to go live also.
> 
> Works now, thanks! (resolved by [paritytech/polkadot-cloud@0747c8a](https://github.com/paritytech/polkadot-cloud/commit/0747c8a07afa6125a363da686255db5c3e646f25)?)

Excellent, thanks again for reporting the issue, it has been a huge help. Yes, it seems like the ref `offsetHeight` is not triggering a re-render on its final value, so the `status` dependency needs to be there to ensure it re-renders at the correct height when the transition has completely finished. Maybe the issue will become clearer in due course now the overlay code is isolated in its own package.
